### ISSUE TITLE
cannot install collective.relationhelpers in Plone 4, missing DX imports

### ISSUE THREAD

**Issue by fredvd** [collective/collective.relationhelpers#4]
In the REAME there are notes with  'you can call this function in Plone 4', but when I tried to add collective.relationhelpers to a Plone 4.3.18 site I run into several import errors.  Maybe the package evolved into Plone 5 only? 

first group is in the API and plone.app.iterate. These are not yet available in plone.app.iterate 2.1.X

    from plone.app.iterate.dexterity import ITERATE_RELATION_NAME
    from plone.app.iterate.dexterity.relation import StagingRelationValue

try/excepted those in a local branch, then next import error is:

    from plone.app.linkintegrity.handlers import modifiedContent

That modules seems to be completely refactored since Plone 5, master/Plone 5.x has `modifiedContent`, in plone.app.linkintegrity 1.5.10 there are 
`modifiedDexterity` and `modifiedArchetypes` functions....

**Comment by pbauer** [comment]
This plackage is not intended to be installed in Plone 4 at all. 

The example from https://github.com/collective/collective.relationhelpers#dealing-with-archetypes-relations is not depending on this package at all. It only requires plone.app.contenttypes and plone.api. 

```
def store_relations(context=None):
    from plone.app.contenttypes.migration.utils import store_references
    portal = api.portal.get()
    store_references(portal)
```
